### ISSUE TITLE
Responsive example does not work.

### ISSUE THREAD

**Issue by BradleyJHumble** [ItsMrAkhil/react-styled-carousel#28]
reponsive => responsive. 
I for the life of me was wondering why it wasn't working then realize there is a typo in the example given.

**Comment by ItsMrAkhil** [comment]
@BradleyJHumble Can you create a pull request for the same. And sorry for the mistake.

**Comment by BradleyJHumble** [comment]
Sorry late response but Mate it's your ReadMe file not the running example. The second example given in your ReadMe has a misspelling and is a bit much for a pull.
