### ISSUE TITLE
Warning: Can't call setState (or forceUpdate) on an unmounted component.

### ISSUE THREAD

**Issue by yyynnn** [ItsMrAkhil/react-styled-carousel#30]
Getting this in latest react on first slide transition:
`warning.js:33 Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`

**Comment by ItsMrAkhil** [comment]
Closing issue as due to inactivity.
