### ISSUE TITLE
Warning: It looks like there are several instances of 'styled-components' initialized in this application. 

### ISSUE THREAD

**Issue by TylerBarnes** [ItsMrAkhil/react-styled-carousel#32]
Hey there, thanks for the great component!

I'm using this component with gatsbyjs and styled components alongside `react-styled-carousel`.
I'm getting this error
```
It looks like there are several instances of 'styled-components' initialized in this application. This may cause dynamic styles not rendering properly, errors happening during rehydration process and makes your application bigger without a good reason.

See https://s-c.sh/2BAXzed for more info.
```

Is there a way for me to prevent `react-styled-carousel` from loading styled components as well?

If I remove `react-styled-carousel` the error goes away.

**Comment by TylerBarnes** [comment]
I could be wrong but checking out package.json I believe react and styled components should only be peer dependencies but it looks like they're duplicated in to peer dependencies and dependencies.

**Comment by ItsMrAkhil** [comment]
@TylerBarnes Feel free to reopen the issue if you think it's an issue. And add more details
