### ISSUE TITLE
issue auto not working

### ISSUE THREAD

**Issue by appasaheb4** [ItsMrAkhil/react-styled-carousel#35]
<img width="1411" alt="Screenshot 2019-03-16 at 10 32 47 AM" src="https://user-images.githubusercontent.com/24726539/54470973-24a75e80-47d7-11e9-94f7-7cf1a5959cfa.png">

    <Slider
              autoSlide={2000}
              padding={"50px"}
              cardsToShow={3}
              reponsive={responsive}
            >
              {repolist}
            </Slider>

const repolist = this.state.repoList.map((item: any) => (
      <GithubLoginButton
        style={btnGithub}
        onClick={() => this.routeChange(item.html_url)}
      >
        <span>{item.name}</span>
      </GithubLoginButton>
    ));

//slider auto not working

**Comment by ItsMrAkhil** [comment]
@appasaheb4 Can you please check your console. It's working fine here.

Feel free to reopen the issue if you still facing it. But with more information.
