### ISSUE TITLE
Strange issue management

### ISSUE THREAD

**Issue by TylerBarnes** [ItsMrAkhil/react-styled-carousel#36]
@TylerBarnes Feel free to reopen the issue if you think it's an issue. And add more details

_Originally posted by @ItsMrAkhil in https://github.com/ItsMrAkhil/react-styled-carousel/issues/32#issuecomment-473622715_

Hey @ItsMrAkhil,
I stopped using react-styled-carousel because of this error but if I didn't think it was an issue I wouldn't have opened an issue in the first place. Why does the issue need to be opened twice for it to be considered an issue? 
It also seems I can't reopen issues here.

What other details do you want? The issue was fairly specific. 
If you just want to close the issue to not deal with it, it's probably better to say that when you're closing it.

**Comment by ItsMrAkhil** [comment]
@TylerBarnes I didn't understand your problem exactly. And it was in the issues for a long time. As I was packed by my professional stuff I didn't get time to fix the issues in recent times. Thanks for creating the issue. I'll fix it as early as possible. And I'm really sorry for closing the issue.

**Comment by TylerBarnes** [comment]
@ItsMrAkhil no worries! I realized today my response was a little harsh, sorry for that.
If I get a sec I should submit a PR. I know maintaining open source stuff is hard!
Thanks
