### ISSUE TITLE
Remove lodash sortby

### ISSUE THREAD

**Issue by idarbuashvili** [ItsMrAkhil/react-styled-carousel#38]
Hi, removing lodash.sortby and making it by hand should significantly reduce the size of the package. If you check https://bundlephobia.com/result?p=react-styled-carousel@0.5.1, you will see that nearly half of the library is lodash sortby. I checked the source and the function is used only in one place, so it should be quite ok to rewrite that portion with custom sort by code.

**Comment by ItsMrAkhil** [comment]
@idarbuashvili That's a valuable comment. I'll surely look into it.

**Comment by idarbuashvili** [comment]
Made the #39 pull request, this should do the job. :)
